version: "3.8"

services:

  fastchat-controller:
    image: fastchat:latest
    environment:
      TZ: Asia/Shanghai
    ports:
      - "21001:21001"
    entrypoint:
      [
        "python3.9",
        "-m",
        "fastchat.serve.controller",
        "--host",
        "0.0.0.0",
        "--port",
        "21001"
      ]

  fastchat-model-worker:
    image: fastchat:latest
    environment:
      TZ: Asia/Shanghai
      FASTCHAT_CONTROLLER_URL: http://fastchat-controller:21001
    volumes:
      - /mnt/data/models:/mnt/data/models
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              device_ids: [ '2' ]
              capabilities: [ "gpu" ]
    entrypoint:
      [
        "python3.9",
        "-m",
        "fastchat.serve.model_worker",
        "--model-path",
        "/mnt/data/models/chatglm2-6b",
        "--worker-address",
        "http://10.56.24.62:21002",
        "--controller-address",
        "http://10.56.24.62:21001",
        "--host",
        "0.0.0.0",
        "--port",
        "21002"
      ]
    ports:
      - "21002:21002"
    depends_on:
      - fastchat-controller

  fastchat-webui:
    image: fastchat:latest
    environment:
      TZ: Asia/Shanghai
    ports:
      - "21000:21000"
    entrypoint:
      [
        "python3.9",
        "-m",
        "fastchat.serve.gradio_web_server",
        "--port",
        "21000",
        "--controller-url",
        "http://fastchat-controller:21001"
      ]
    depends_on:
      - fastchat-controller
      - fastchat-model-worker

  fastchat-api-server:
    environment:
      FASTCHAT_CONTROLLER_URL: http://fastchat-controller:21001
    image: fastchat:latest
    ports:
      - "21003:21003"
    entrypoint:
      [
        "python3.9",
        "-m",
        "fastchat.serve.openai_api_server",
        "--controller-address",
        "http://fastchat-controller:21001",
        "--host",
        "0.0.0.0",
        "--port",
        "21003"
      ]

networks:
  default:
    name: fast-chat
